# Generated by Django 4.1.6 on 2023-02-08 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ManyToManyField(related_name='user_skills', to='administration.skill')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, null=True)),
                ('working_on_the_project', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='Describe about yourself.', max_length=500, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('github_url', models.URLField(blank=True, max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='license_certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('issuing_organization', models.CharField(max_length=60, null=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True)),
                ('credential_id', models.CharField(blank=True, max_length=40, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=300, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institue_name', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('feild_of_study', models.CharField(blank=True, max_length=80, null=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('activities_societies', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, null=True)),
                ('about_company', models.TextField(max_length=600, null=True)),
                ('comapny_short_description', models.CharField(max_length=100, null=True)),
                ('company_location', models.TextField(max_length=400, null=True)),
                ('website_url', models.URLField(max_length=150, null=True)),
                ('comapny_logo', models.ImageField(upload_to='company_image')),
                ('founded', models.IntegerField(help_text='Please provide only the founded year.')),
                ('company_size', models.IntegerField(help_text='Provide the current size of the company.')),
                ('Specialties', models.TextField(max_length=300, null=True)),
                ('company_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
