# Generated by Django 4.1.6 on 2023-04-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_company_profile_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_profile',
            old_name='about_comapny',
            new_name='about_company',
        ),
    ]
